services:
  apache:
    image: wordpress:php8.3-apache # arm64v8/wordpress:php8.3-apache
    volumes:
      - './web/:/var/www/html'
      - './entrypoint.sh:/entrypoint.sh'
    entrypoint: ["/entrypoint.sh", "apache2"]
    environment:
      VIRTUAL_HOST: wordpress.docker.casa
      VIRTUAL_PORT: 80
      OWNER_UID: 1000
      OWNER_GID: 1000
      WORDPRESS_DB_HOST: mysql:3306 # Local MySQL or container
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
      DEV_MODE: 1
    network_mode: bridge
  mysql: # If no local MySQL
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    network_mode: bridge
