services:
  apache:
    image: wordpress:php8.0-apache
    volumes:
      - ./web/:/var/www/html
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh", "apache2"]
    environment:
      LETSENCRYPT_HOST: dxo.docker.casa
      VIRTUAL_HOST: dxo.docker.casa
      OWNER_UID: 1000
      OWNER_GID: 1000
    networks:
      - nginx-proxy
networks:
  nginx-proxy:
    external: true